package com.wf.hackathon.service.ai;

import java.util.HashMap;
import java.util.Map;

public class Constants
{
static final String SPEECH__SUBSCRIPTION__KEY = "1140d6c40d6a4f32bfa09d9270d1c509";
static final String SPEECH__SERVICE__REGION = "eastus";
static final String SPEECH_SOURCE_LANG="en-US";
static final String SPEECH_TARGET_LANG="en";
static final String FEMALE="Female";
static final String SPEED_SLOW="slow";
static final String SPEED_NORMAL="normal";
static final String SPEED_FAST="fast";

static final Map<String,String> femaleVoiceMap= new HashMap<String,String>();
static final Map<String,String> maleVoiceMap= new HashMap<String,String>();
static final Map<String,String> langMap= new HashMap<String,String>(); 
static{
    langMap.put("Afghanistan","ps-AF");
    langMap.put("Algeria","ar-DZ");
    langMap.put("Argentina","es-AR");
    langMap.put("Australia","en-AU");
    langMap.put("Austria","de-AT");
    langMap.put("Bahrain","ar-BH");
    langMap.put("Bangladesh","bn-BD");
    langMap.put("Belgium","nl-BE");
    langMap.put("Bokmål, Norway","nb-NO");
    langMap.put("Bolivia","es-BO");
    langMap.put("Brazil","pt-BR");
    langMap.put("Bulgaria","bg-BG");
    langMap.put("Cambodia","km-KH");
    langMap.put("Canada","fr-CA");
    langMap.put("Cantonese","zh-HK");
    langMap.put("Chile","es-CL");
    langMap.put("Colombia","es-CO");
    langMap.put("Costa Rica","es-CR");
    langMap.put("Croatia","hr-HR");
    langMap.put("Cuba","es-CU");
    langMap.put("Czech","cs-CZ");
    langMap.put("Denmark","da-DK");
    langMap.put("Dominican Republic","es-DO");
    langMap.put("Ecuador","es-EC");
    langMap.put("Egypt","ar-EG");
    langMap.put("El Salvador","es-SV");
    langMap.put("Equatorial Guinea","es-GQ");
    langMap.put("Estonia","et-EE");
    langMap.put("Ethiopia","am-ET");
    langMap.put("Finland","fi-FI");
    langMap.put("France","fr-FR");
    langMap.put("Germany","de-DE");
    langMap.put("Greece","el-GR");
    langMap.put("Guatemala","es-GT");
    langMap.put("Honduras","es-HN");
    langMap.put("Hongkong","en-HK");
    langMap.put("Hungary","hu-HU");
    langMap.put("Iceland","is-IS");
    langMap.put("India","hi-IN");
    langMap.put("Indonesia","jv-ID");
    langMap.put("Iran","fa-IR");
    langMap.put("Iraq","ar-IQ");
    langMap.put("Ireland","ga-IE");
    langMap.put("Israel","he-IL");
    langMap.put("Italy","it-IT");
    langMap.put("Japan","ja-JP");
    langMap.put("Jordan","ar-JO");
    langMap.put("Kazakhstan","kk-KZ");
    langMap.put("Kenya","sw-KE");
    langMap.put("Korea","ko-KR");
    langMap.put("Kuwait","ar-KW");
    langMap.put("Laos","lo-LA");
    langMap.put("Latvia","lv-LV");
    langMap.put("Libya","ar-LY");
    langMap.put("Lithuania","lt-LT");
    langMap.put("Malaysia","ms-MY");
    langMap.put("Malta","mt-MT");
    langMap.put("China","zh-CN");
    langMap.put("Mexico","es-MX");
    langMap.put("Morocco","ar-MA");
    langMap.put("Myanmar","my-MM");
    langMap.put("Netherlands","nl-NL");
    langMap.put("New Zealand","en-NZ");
    langMap.put("Nicaragua","es-NI");
    langMap.put("Nigeria","en-NG");
    langMap.put("Pakistan","ur-PK");
    langMap.put("Panama","es-PA");
    langMap.put("Paraguay","es-PY");
    langMap.put("Peru","es-PE");
    langMap.put("Philippines","fil-PH");
    langMap.put("Poland","pl-PL");
    langMap.put("Portugal","pt-PT");
    langMap.put("Puerto Rico","es-PR");
    langMap.put("Qatar","ar-QA");
    langMap.put("Republic of North Macedonia","mk-MK");
    langMap.put("Romania","ro-RO");
    langMap.put("Russia","ru-RU");
    langMap.put("Saudi Arabia","ar-SA");
    langMap.put("Serbia, Cyrillic","sr-RS");
    langMap.put("Singapore","ta-SG");
    langMap.put("Slovakia","sk-SK");
    langMap.put("Slovenia","sl-SI");
    langMap.put("Somalia","so-SO");
    langMap.put("South Africa","zu-ZA");
    langMap.put("Spain","ca-ES");
    langMap.put("Sri Lanka","ta-LK");
    langMap.put("Sweden","sv-SE");
    langMap.put("Switzerland","fr-CH");
    langMap.put("Syria","ar-SY");
    langMap.put("Taiwanese Mandarin","zh-TW");
    langMap.put("Tanzania","sw-TZ");
    langMap.put("Thailand","th-TH");
    langMap.put("Tunisia","ar-TN");
    langMap.put("Turkey","tr-TR");
    langMap.put("Ukraine","uk-UA");
    langMap.put("United Arab Emirates","ar-AE");
    langMap.put("United Kingdom","en-GB");
    langMap.put("United States","en-US");
    langMap.put("Uruguay","es-UY");
    langMap.put("Uzbekistan","uz-UZ");
    langMap.put("Venezuela","es-VE");
    langMap.put("Vietnam","vi-VN");
    langMap.put("Yemen","ar-YE");

}
static{
    maleVoiceMap.put("Afghanistan","ps-AF-GulNawazNeural New");
    maleVoiceMap.put("Algeria","ar-DZ-IsmaelNeural");
    maleVoiceMap.put("Argentina","es-AR-TomasNeural");
    maleVoiceMap.put("Austria","de-AT-JonasNeural");
    maleVoiceMap.put("Bahrain","ar-BH-AliNeural");
    maleVoiceMap.put("Bangladesh","bn-BD-PradeepNeural");
    maleVoiceMap.put("Belgium","nl-BE-ArnaudNeural");
    maleVoiceMap.put("Bokmål, Norway","nb-NO-FinnNeural");
    maleVoiceMap.put("Bolivia","es-BO-MarceloNeural");
    maleVoiceMap.put("Brazil","pt-BR-AntonioNeural");
    maleVoiceMap.put("Bulgaria","bg-BG-BorislavNeural");
    maleVoiceMap.put("Cambodia","km-KH-PisethNeural");
    maleVoiceMap.put("Canada","fr-CA-JeanNeural");
    maleVoiceMap.put("Cantonese","zh-HK-WanLungNeural");
    maleVoiceMap.put("China","zh-CN-YunxiNeural");
    maleVoiceMap.put("Chile","es-CL-LorenzoNeural");
    maleVoiceMap.put("Colombia","es-CO-GonzaloNeural");
    maleVoiceMap.put("Costa Rica","es-CR-JuanNeural");
    maleVoiceMap.put("Croatia","hr-HR-SreckoNeural");
    maleVoiceMap.put("Cuba","es-CU-ManuelNeural");
    maleVoiceMap.put("Czech","cs-CZ-AntoninNeural");
    maleVoiceMap.put("Denmark","da-DK-JeppeNeural");
    maleVoiceMap.put("Dominican Republic","es-DO-EmilioNeural");
    maleVoiceMap.put("Ecuador","es-EC-LuisNeural");
    maleVoiceMap.put("Egypt","ar-EG-ShakirNeural");
    maleVoiceMap.put("El Salvador","es-SV-RodrigoNeural");
    maleVoiceMap.put("Equatorial Guinea","es-GQ-JavierNeural");
    maleVoiceMap.put("Estonia","et-EE-KertNeural");
    maleVoiceMap.put("Ethiopia","am-ET-AmehaNeural");
    maleVoiceMap.put("Finland","fi-FI-HarriNeural");
    maleVoiceMap.put("France","fr-FR-HenriNeural");
    maleVoiceMap.put("Germany","de-DE-ConradNeural");
    maleVoiceMap.put("Greece","el-GR-NestorasNeural");
    maleVoiceMap.put("Guatemala","es-GT-AndresNeural");
    maleVoiceMap.put("Honduras","es-HN-CarlosNeural");
    maleVoiceMap.put("Hongkong","en-HK-SamNeural");
    maleVoiceMap.put("Hungary","hu-HU-TamasNeural");
    maleVoiceMap.put("Iceland","is-IS-GunnarNeural New");
    maleVoiceMap.put("India","hi-IN-MadhurNeural");
    maleVoiceMap.put("Indonesia","jv-ID-DimasNeural");
    maleVoiceMap.put("Iran","fa-IR-FaridNeural");
    maleVoiceMap.put("Ireland","ga-IE-ColmNeural");
    maleVoiceMap.put("Israel","he-IL-AvriNeural");
    maleVoiceMap.put("Italy","it-IT-DiegoNeural");
    maleVoiceMap.put("Japan","ja-JP-KeitaNeural");
    maleVoiceMap.put("Jordan","ar-JO-TaimNeural");
    maleVoiceMap.put("Kazakhstan","kk-KZ-DauletNeural New");
    maleVoiceMap.put("Kenya","sw-KE-RafikiNeural");
    maleVoiceMap.put("Korea","ko-KR-InJoonNeural");
    maleVoiceMap.put("Kuwait","ar-KW-FahedNeural");
    maleVoiceMap.put("Laos","lo-LA-ChanthavongNeural New");
    maleVoiceMap.put("Latvia","lv-LV-NilsNeural");
    maleVoiceMap.put("Libya","ar-LY-OmarNeural");
    maleVoiceMap.put("Lithuania","lt-LT-LeonasNeural");
    maleVoiceMap.put("Malaysia","ms-MY-OsmanNeural");
    maleVoiceMap.put("Malta","mt-MT-JosephNeural");
    maleVoiceMap.put("Mexico","es-MX-JorgeNeural");
    maleVoiceMap.put("Morocco","ar-MA-JamalNeural");
    maleVoiceMap.put("Myanmar","my-MM-ThihaNeural");
    maleVoiceMap.put("Netherlands","nl-NL-MaartenNeural");
    maleVoiceMap.put("New Zealand","en-NZ-MitchellNeural");
    maleVoiceMap.put("Nicaragua","es-NI-FedericoNeural");
    maleVoiceMap.put("Nigeria","en-NG-AbeoNeural");
    maleVoiceMap.put("Pakistan","ur-PK-AsadNeural");
    maleVoiceMap.put("Panama","es-PA-RobertoNeural");
    maleVoiceMap.put("Paraguay","es-PY-MarioNeural");
    maleVoiceMap.put("Peru","es-PE-AlexNeural");
    maleVoiceMap.put("Philippines","fil-PH-AngeloNeural");
    maleVoiceMap.put("Poland","pl-PL-MarekNeural");
    maleVoiceMap.put("Portugal","pt-PT-DuarteNeural");
    maleVoiceMap.put("Puerto Rico","es-PR-VictorNeural");
    maleVoiceMap.put("Qatar","ar-QA-MoazNeural");
    maleVoiceMap.put("Republic of North Macedonia","mk-MK-AleksandarNeural New");
    maleVoiceMap.put("Romania","ro-RO-EmilNeural");
    maleVoiceMap.put("Russia","ru-RU-DmitryNeural");
    maleVoiceMap.put("Saudi Arabia","ar-SA-HamedNeural");
    maleVoiceMap.put("Serbia, Cyrillic","sr-RS-NicholasNeural New");
    maleVoiceMap.put("Singapore","ta-SG-AnbuNeural");
    maleVoiceMap.put("Slovakia","sk-SK-LukasNeural");
    maleVoiceMap.put("Slovenia","sl-SI-RokNeural");
    maleVoiceMap.put("Somalia","so-SO-MuuseNeural");
    maleVoiceMap.put("South Africa","af-ZA-WillemNeural");
    maleVoiceMap.put("Spain","ca-ES-EnricNeural");
    maleVoiceMap.put("Sri Lanka","ta-LK-KumarNeural");
    maleVoiceMap.put("Sweden","sv-SE-MattiasNeural");
    maleVoiceMap.put("Switzerland","de-CH-JanNeural");
    maleVoiceMap.put("Syria","ar-SY-LaithNeural");
    maleVoiceMap.put("Taiwan","zh-TW-YunJheNeural");
    maleVoiceMap.put("Tanzania","sw-TZ-DaudiNeural");
    maleVoiceMap.put("Thailand","th-TH-NiwatNeural");
    maleVoiceMap.put("Tunisia","ar-TN-HediNeural");
    maleVoiceMap.put("Turkey","tr-TR-AhmetNeural");
    maleVoiceMap.put("Ukraine","uk-UA-OstapNeural");
    maleVoiceMap.put("United Arab Emirates","ar-AE-HamdanNeural");
    maleVoiceMap.put("United States","en-US-BrandonNeural");
    maleVoiceMap.put("Uruguay","es-UY-MateoNeural");
    maleVoiceMap.put("Uzbekistan","uz-UZ-SardorNeural");
    maleVoiceMap.put("Venezuela","es-VE-SebastianNeural");
    maleVoiceMap.put("Vietnam","vi-VN-NamMinhNeural");
    maleVoiceMap.put("Yemen","ar-YE-SalehNeural");

}
static{
    femaleVoiceMap.put("Afghanistan","ps-AF-LatifaNeural New");
    femaleVoiceMap.put("Algeria","ar-DZ-AminaNeural");
    femaleVoiceMap.put("Argentina","es-AR-ElenaNeural");
    femaleVoiceMap.put("Australia","en-AU-NatashaNeural");
    femaleVoiceMap.put("Austria","de-AT-IngridNeural");
    femaleVoiceMap.put("Bahrain","ar-BH-LailaNeural");
    femaleVoiceMap.put("Bangladesh","bn-BD-NabanitaNeural");
    femaleVoiceMap.put("Belgium","nl-BE-DenaNeural");
    femaleVoiceMap.put("Bokmål, Norway","nb-NO-PernilleNeural");
    femaleVoiceMap.put("Bolivia","es-BO-SofiaNeural");
    femaleVoiceMap.put("Brazil","pt-BR-FranciscaNeural");
    femaleVoiceMap.put("Bulgaria","bg-BG-KalinaNeural");
    femaleVoiceMap.put("Cambodia","km-KH-SreymomNeural");
    femaleVoiceMap.put("Canada","en-CA-ClaraNeural");
    femaleVoiceMap.put("Cantonese","zh-HK-HiuMaanNeural");
    femaleVoiceMap.put("Chile","es-CL-CatalinaNeural");
    femaleVoiceMap.put("Colombia","es-CO-SalomeNeural");
    femaleVoiceMap.put("Costa Rica","es-CR-MariaNeural");
    femaleVoiceMap.put("Croatia","hr-HR-GabrijelaNeural");
    femaleVoiceMap.put("Cuba","es-CU-BelkysNeural");
    femaleVoiceMap.put("Czech","cs-CZ-VlastaNeural");
    femaleVoiceMap.put("Denmark","da-DK-ChristelNeural");
    femaleVoiceMap.put("Dominican Republic","es-DO-RamonaNeural");
    femaleVoiceMap.put("Ecuador","es-EC-AndreaNeural");
    femaleVoiceMap.put("Egypt","ar-EG-SalmaNeural");
    femaleVoiceMap.put("El Salvador","es-SV-LorenaNeural");
    femaleVoiceMap.put("Equatorial Guinea","es-GQ-TeresaNeural");
    femaleVoiceMap.put("Estonia","et-EE-AnuNeural");
    femaleVoiceMap.put("Ethiopia","am-ET-MekdesNeural");
    femaleVoiceMap.put("Finland","fi-FI-NooraNeural");
    femaleVoiceMap.put("France","fr-FR-DeniseNeural");
    femaleVoiceMap.put("Germany","de-DE-KatjaNeural");
    femaleVoiceMap.put("Greece","el-GR-AthinaNeural");
    femaleVoiceMap.put("Guatemala","es-GT-MartaNeural");
    femaleVoiceMap.put("Honduras","es-HN-KarlaNeural");
    femaleVoiceMap.put("Hongkong","en-HK-YanNeural");
    femaleVoiceMap.put("Hungary","hu-HU-NoemiNeural");
    femaleVoiceMap.put("Iceland","is-IS-GudrunNeural New");
    femaleVoiceMap.put("India","hi-IN-SwaraNeural");
    femaleVoiceMap.put("Indonesia","id-ID-GadisNeural");
    femaleVoiceMap.put("Iran","fa-IR-DilaraNeural");
    femaleVoiceMap.put("Ireland","ga-IE-OrlaNeural");
    femaleVoiceMap.put("Israel","he-IL-HilaNeural");
    femaleVoiceMap.put("Italy","it-IT-IsabellaNeural");
    femaleVoiceMap.put("Japan","ja-JP-NanamiNeural");
    femaleVoiceMap.put("Jordan","ar-JO-SanaNeural");
    femaleVoiceMap.put("Kazakhstan","kk-KZ-AigulNeural New");
    femaleVoiceMap.put("Kenya","sw-KE-ZuriNeural");
    femaleVoiceMap.put("Korea","ko-KR-SunHiNeural");
    femaleVoiceMap.put("Kuwait","ar-KW-NouraNeural");
    femaleVoiceMap.put("Laos","lo-LA-KeomanyNeural New");
    femaleVoiceMap.put("Latvia","lv-LV-EveritaNeural");
    femaleVoiceMap.put("Libya","ar-LY-ImanNeural");
    femaleVoiceMap.put("Lithuania","lt-LT-OnaNeural");
    femaleVoiceMap.put("Malaysia","ms-MY-YasminNeural");
    femaleVoiceMap.put("Malta","mt-MT-GraceNeural");
    femaleVoiceMap.put("China","zh-CN-XiaochenNeural");
    femaleVoiceMap.put("Mexico","es-MX-DaliaNeural");
    femaleVoiceMap.put("Morocco","ar-MA-MounaNeural");
    femaleVoiceMap.put("Myanmar","my-MM-NilarNeural");
    femaleVoiceMap.put("Netherlands","nl-NL-FennaNeural");
    femaleVoiceMap.put("New Zealand","en-NZ-MollyNeural");
    femaleVoiceMap.put("Nicaragua","es-NI-YolandaNeural");
    femaleVoiceMap.put("Nigeria","en-NG-EzinneNeural");
    femaleVoiceMap.put("Pakistan","ur-PK-UzmaNeural");
    femaleVoiceMap.put("Panama","es-PA-MargaritaNeural");
    femaleVoiceMap.put("Paraguay","es-PY-TaniaNeural");
    femaleVoiceMap.put("Peru","es-PE-CamilaNeural");
    femaleVoiceMap.put("Philippines","fil-PH-BlessicaNeural");
    femaleVoiceMap.put("Poland","pl-PL-ZofiaNeural");
    femaleVoiceMap.put("Portugal","pt-PT-FernandaNeural");
    femaleVoiceMap.put("Puerto Rico","es-PR-KarinaNeural");
    femaleVoiceMap.put("Qatar","ar-QA-AmalNeural");
    femaleVoiceMap.put("Republic of North Macedonia","mk-MK-MarijaNeural New");
    femaleVoiceMap.put("Romania","ro-RO-AlinaNeural");
    femaleVoiceMap.put("Russia","ru-RU-DariyaNeural");
    femaleVoiceMap.put("Saudi Arabia","ar-SA-ZariyahNeural");
    femaleVoiceMap.put("Serbia, Cyrillic","sr-RS-SophieNeural New");
    femaleVoiceMap.put("Singapore","ta-SG-VenbaNeural");
    femaleVoiceMap.put("Slovakia","sk-SK-ViktoriaNeural");
    femaleVoiceMap.put("Slovenia","sl-SI-PetraNeural");
    femaleVoiceMap.put("Somalia","so-SO-UbaxNeural");
    femaleVoiceMap.put("South Africa","af-ZA-AdriNeural");
    femaleVoiceMap.put("South Africa","zu-ZA-ThandoNeural");
    femaleVoiceMap.put("Spain","ca-ES-AlbaNeural");
    femaleVoiceMap.put("Spain","gl-ES-SabelaNeural");
    femaleVoiceMap.put("Sri Lanka","si-LK-ThiliniNeural New");
    femaleVoiceMap.put("Sweden","sv-SE-HilleviNeural");
    femaleVoiceMap.put("Switzerland","de-CH-LeniNeural");
    femaleVoiceMap.put("Syria","ar-SY-AmanyNeural");
    femaleVoiceMap.put("Taiwan","zh-TW-HsiaoChenNeural");
    femaleVoiceMap.put("Tanzania","sw-TZ-RehemaNeural");
    femaleVoiceMap.put("Thailand","th-TH-AcharaNeural");
    femaleVoiceMap.put("Tunisia","ar-TN-ReemNeural");
    femaleVoiceMap.put("Turkey","tr-TR-EmelNeural");
    femaleVoiceMap.put("Ukraine","uk-UA-PolinaNeural");
    femaleVoiceMap.put("United Arab Emirates","ar-AE-FatimaNeural");
    femaleVoiceMap.put("United Kingdom","cy-GB-NiaNeural");
    femaleVoiceMap.put("United States","en-US-JennyMultilingualNeural");
    femaleVoiceMap.put("Uruguay","es-UY-ValentinaNeural");
    femaleVoiceMap.put("US","es-US-PalomaNeural");
    femaleVoiceMap.put("Uzbekistan","uz-UZ-MadinaNeural");
    femaleVoiceMap.put("Venezuela","es-VE-PaolaNeural");
    femaleVoiceMap.put("Vietnam","vi-VN-HoaiMyNeural");
    femaleVoiceMap.put("Yemen","ar-YE-MaryamNeural");

    }

}